import './harness/loader.mjs';
import assert from 'node:assert/strict';
import { accessHarness, syntheticPlan, syntheticEvent } from './harness/access.mjs';
const { validateAccessPlan, permitsAccess, selectAccessChoice, accessDigest } = await import('../src/lib/access-contracts.ts');
const { issue, issueIssuer, verify } = await import('../src/lib/tokens.ts');
import { TEST_SECRET } from './harness/index.mjs';

const h=await accessHarness(),{request:q,env,student,instructor}=h;
const post=(path,body,auth)=>q(path,{method:'POST',body,auth});
const put=(path,body,auth)=>q(path,{method:'PUT',body,auth});
const ok=async(p,status=200)=>{const r=await p;assert.equal(r.status,status,r.text);return r.json;};
try {
  const plan=syntheticPlan();
  await ok(post('/admin/access/plans',plan),201);
  await ok(post('/admin/access/plans',plan),201);
  await ok(post('/admin/access/plans',{...plan,label:'changed'}),409);
  for(const broken of [{...plan,included:[]},{...plan,policy:{...plan.policy,overage:'charge'}},{...plan,allowed:{...plan.allowed,features:['*']}},{...plan,sale:{currency:'USD',minor_units:0.5}},{...plan,mode:'byo'},{...plan,policy:{...plan.policy,timezone:'not/a/timezone'}}])assert.throws(()=>validateAccessPlan(broken));
  env.ENVIRONMENT='production';await ok(post('/admin/access/plans',syntheticPlan('synthetic-prod')),403);env.ENVIRONMENT='dev';
  const approved={...syntheticPlan('approved-1'),publication:'approved',approval_ref:'synthetic-review-only'};
  await ok(post('/admin/access/plans',approved),403);
  env.HPS_ACCESS_APPROVED_PLAN_DIGESTS=await accessDigest(approved);await ok(post('/admin/access/plans',approved),201);
  await ok(post('/admin/access/plans',{...approved,label:'tampered'}),403);
  console.log('PASS publication immutability, exact approval digest and incomplete/unsupported pricing denial');

  const e=syntheticEvent();await ok(post('/admin/access/events',e));
  assert.equal((await ok(post('/admin/access/events',e))).applied,false);
  await ok(post('/admin/access/events',{...e,state:'ended'}),409);
  const paused={...e,event_id:'paused',source_version:3,state:'suspended'};
  await ok(post('/admin/access/events',paused));
  await ok(post('/admin/access/events',{...e,event_id:'late-v2',source_version:2}));
  assert.equal((await ok(q('/v1/access',{auth:student}))).choices[0].active,false,'suspended contract remains readable but cannot execute');
  await ok(post('/admin/access/events',{...e,event_id:'resume',source_version:4}));
  assert.equal((await ok(q('/v1/access',{auth:student}))).choices.length,1);
  assert.equal(h.db.prepare('SELECT COUNT(*) n FROM access_periods').get().n,1);
  await ok(post('/admin/access/events',{...e,event_id:'different-owner',source_version:5,payer:{kind:'account',id:'other'}}),409);
  await ok(post('/admin/access/events',{...e,event_id:'alter-period',source_version:5,period:{...e.period,ends_at:e.period.ends_at+1000}}),409);
  assert.equal(h.db.prepare('SELECT source_version FROM access_contracts').get().source_version,4,'failed period mutation rolls back the head');
  await ok(post('/admin/access/events',{...e,event_id:'overlap',source_version:5,period:{...e.period,id:'overlap-period'}}),409);
  await ok(post('/admin/access/events',{...e,event_id:'premature-renewal',source_version:5,period:{id:'future',starts_at:e.period.ends_at,ends_at:e.period.ends_at+3600000}}),409);
  console.log('PASS duplicate, late, suspension/resume, immutable ownership/period and rollback controls');

  await ok(put('/admin/access/accounts/personal-1',{user_id:'personal-user',profile_id:'studio-model-practice',active:true}));
  await ok(put('/admin/access/accounts/personal-1',{user_id:'hijack',profile_id:'studio-model-practice',active:true}),409);
  const token=(await ok(post('/admin/access/accounts/personal-1/token',{hours:1}))).token;
  const personal='Bearer '+token,p=await verify(token,TEST_SECRET);assert.equal(p.c,'');assert.equal(p.account,'personal-1');
  assert.equal((await ok(q('/v1/access',{auth:personal}))).choices.length,0,'login never grants usage');
  await ok(post('/admin/access/events',syntheticEvent('contract-personal','account','personal-1')));
  assert.equal((await ok(q('/v1/access',{auth:personal}))).choices.length,1);
  await ok(put('/admin/access/accounts/personal-1/seats',{cohort_id:h.cohort,user_id:'kid01'}));
  assert.equal((await ok(q('/v1/access',{auth:student}))).choices.length,1,'class denies personal funding by default');
  await ok(put('/admin/access/cohorts/'+h.cohort+'/policy',{expected_revision:0,required:true,allow_personal:true}));
  await ok(put('/admin/access/cohorts/'+h.cohort+'/policy',{expected_revision:0,required:true,allow_personal:false}),409);
  const hybrid=await ok(q('/v1/access',{auth:student}));assert.equal(hybrid.choices.length,2);assert.equal(hybrid.selection_required,true);
  assert.throws(()=>selectAccessChoice([],undefined),/funding_selection_required/);
  assert.throws(()=>selectAccessChoice([], 'missing'),/funding_unavailable/);
  assert(permitsAccess({plan},{model:'gpt-5.6-luna',runtime:'proxy',effort:'low',features:[]}));
  assert(!permitsAccess({plan},{model:'gpt-5.6-luna',runtime:'proxy',effort:'high',features:[]}));
  assert(!permitsAccess({plan},{model:'gpt-5.6-luna',runtime:'proxy',effort:'low',features:['browser']}));
  const other='Bearer '+(await issue({u:'kid02',c:h.cohort,p:h.profile},1,TEST_SECRET)).token;
  assert.equal((await ok(q('/v1/access',{auth:other}))).choices.length,1);
  await ok(put('/admin/access/organizations/org-1',{}));
  await ok(put('/admin/access/organizations/org-1/members/personal-1',{}));
  await ok(post('/admin/access/events',syntheticEvent('contract-org','organization','org-1')));
  assert.equal((await ok(q('/v1/access',{auth:personal}))).choices.length,2);
  assert.equal((await ok(q('/v1/access',{auth:other}))).choices.length,1);
  await ok(put('/admin/access/accounts/personal-1',{user_id:'personal-user',profile_id:'studio-model-practice',active:false}));
  await ok(q('/v1/access',{auth:personal}),403);
  console.log('PASS independent personal identity, hybrid explicit choice, org membership and account revocation');

  const outsider='Bearer '+(await issueIssuer({issuer:'outsider',scopes:[{cohort:'other',profiles:[h.profile]}]},1,TEST_SECRET)).token;
  await ok(q('/admin/cohorts/'+h.cohort+'/access',{auth:instructor}));
  await ok(q('/admin/cohorts/'+h.cohort+'/access',{auth:outsider}),403);
  await ok(q('/admin/cohorts/'+h.cohort+'/access',{auth:student}),403);
  await ok(post('/admin/access/events',e,instructor),401);
  await ok(post('/admin/access/plans',plan,student),401);
  await ok(q('/v1/access',{auth:instructor}),403);
  await ok(q('/v1/access',{auth:'Bearer invalid'}),401);
  const reissued='Bearer '+(await issue({u:'kid01',c:h.cohort,p:h.profile},1,TEST_SECRET)).token;
  await ok(q('/v1/access',{auth:reissued}),403); // Revoked linked account cannot become an unlinked seat via token reissue.
  env.HPS_ACCESS_CONTRACTS=undefined;
  assert.equal((await ok(q('/v1/access',{auth:student}))).configured,false);
  await ok(q('/admin/cohorts'));
  await ok(post('/admin/access/events',e),503);
  console.log('PASS scoped instructor read, write denial, old identity, token reissue and disabled-feature regression');
} finally {h.close();}
