import assert from 'node:assert/strict';
import {localClassroom} from './harness/classroom.mjs';
const f=await localClassroom();const base=`/admin/cohorts/${f.cohort}/classroom/shares`,student='/v1/classroom/shares';let count=0;
const post=(id,patch={})=>({id,recipient_id:'teacher-a',kind:'help',consent:true,duration_minutes:60,content:{prompt:'진료시간을 어떻게 바꾸나요?',response:'가상의 응답',tool_summary:'읽기 완료',verification:'모바일에서 확인'},...patch});
const req=f.request;const create=(id,patch={},token=f.studentToken)=>req(student,'POST',post(id,patch),token);
async function check(name,fn){await fn();count++;console.log('PASS '+name);}
try{
 await check('AT-03 no consent, invalid recipient, unknown content and credential URL are rejected',async()=>{for(const patch of [{consent:false},{recipient_id:'../other'},{content:{all_logs:true}},{content:{artifact_url:'https://name:secret@example.test'}},{duration_minutes:0}])assert.equal((await create('bad',patch)).status,400);assert.equal(f.db.prepare('SELECT count(*) n FROM classroom_shares').get().n,0);});
 await check('AT-07 role, cohort, profile and roster gates fail closed',async()=>{assert.equal((await create('bad',{},f.teacherToken)).status,403);assert.equal((await create('bad',{},await f.student('not-in-roster'))).status,403);assert.equal((await create('bad',{},await f.student('student-a',f.profile,'other'))).status,403);assert.equal((await create('bad',{},'invalid')).status,401);});
 await check('AT-07 child profile cannot opt in using a checkbox alone',async()=>{const token=await f.student('kid01','sk-biopharm-kids-2026-grade-3-4-s1','sk-biopharm-2026-a');assert.equal((await create('child',{},token)).status,403);});
 await check('AT-03 create/retry, attribution, expiry and secret masking',async()=>{const r=await create('share-a',{content:{prompt:'GITHUB_TOKEN='+('a'.repeat(30)),response:'<img src=x onerror=alert(1)>'}});assert.equal(r.status,201,r.raw);assert.equal(r.json.student_id,'student-a');assert.ok(!r.raw.includes('a'.repeat(30)));assert.ok(r.json.expires_at<=Math.floor(Date.now()/1000)+3600);assert.equal((await create('share-a',{content:{prompt:'GITHUB_TOKEN='+('a'.repeat(30)),response:'<img src=x onerror=alert(1)>'}})).status,200);assert.equal((await create('share-a')).status,409);});
 await check('AT-07 list has no prompt/response; only designated teacher opens body and records view',async()=>{const r=await req(base);assert.equal(r.status,200,r.raw);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(r.json.shares.length,1);assert.ok(!r.raw.includes('content')&&!r.raw.includes('<img'));assert.equal((await req(base+'/share-a','GET',undefined,await f.teacher('teacher-b'))).status,404);assert.equal((await req(base+'/share-a','GET',undefined,await f.teacher('teacher-a',['other-profile']))).status,404);assert.equal((await req(base+'/share-a','GET',undefined,await f.teacher('teacher-a',[f.profile],'other'))).status,403);assert.equal((await req(base+'/share-a')).status,200);assert.equal(f.db.prepare('SELECT count(*) n FROM classroom_share_audit').get().n,1);});
 await check('AT-07 audit write failure never releases content',async()=>{f.fail('INSERT INTO classroom_share_audit');const r=await req(base+'/share-a');f.fail('');assert.equal(r.status,500);assert.ok(!r.raw.includes('<img'));});
 await check('AT-05 feedback CAS gives one winner and preserves student resolution authority',async()=>{const body={expected_revision:1,status:'answered',feedback:'시간표를 확인하세요',next_action:'학생이 미리보기 확인'};const rs=await Promise.all([req(base+'/share-a','PUT',body),req(base+'/share-a','PUT',{...body,feedback:'다른 피드백'})]);assert.deepEqual(rs.map(r=>r.status).sort(),[200,409]);assert.equal((await req(base+'/share-a','PUT',{...body,expected_revision:2,status:'resolved'})).status,400);const own=await req(student,'GET',undefined,f.studentToken);assert.equal(own.json.shares[0].revision,2);assert.equal((await req(student+'/share-a/confirm','POST',{expected_revision:2},await f.student('student-b'))).status,409);assert.equal((await req(student+'/share-a/confirm','POST',{expected_revision:2},f.studentToken)).status,200);assert.equal((await req(base+'/share-a','PUT',{...body,expected_revision:3})).status,409);});
 await check('AT-14 owner sees access audit; other students cannot read or delete',async()=>{assert.equal((await req(student+'/share-a/audit','GET',undefined,f.studentToken)).json.audit.length,1);assert.equal((await req(student,'GET',undefined,await f.student('student-b'))).json.shares.length,0);assert.equal((await req(student+'/share-a','DELETE',undefined,await f.student('student-b'))).status,404);});
 await check('AT-14 withdrawal deletes content and audit and immediately closes teacher access',async()=>{assert.equal((await req(student+'/share-a','DELETE',undefined,f.studentToken)).status,200);assert.equal((await req(base+'/share-a')).status,404);assert.equal(f.db.prepare('SELECT count(*) n FROM classroom_share_audit').get().n,0);});
 await check('AT-14 expiry denies reads before cleanup; purge only removes expired shares',async()=>{assert.equal((await create('expired')).status,201);assert.equal((await create('active')).status,201);f.db.prepare('UPDATE classroom_shares SET expires_at=0 WHERE id=?').run('expired');assert.equal((await req(base+'/expired')).status,404);assert.equal((await req(base)).json.shares.length,1);const {purgeExpiredClassroomShares}=await import('../src/routes/classroom.ts');await purgeExpiredClassroomShares(f.env);assert.equal(f.db.prepare('SELECT count(*) n FROM classroom_shares').get().n,1);});
 await check('AT-07 revoked students and instructors lose access',async()=>{const {verify}=await import('../src/lib/tokens.ts');const p=await verify(f.studentToken,f.env.HPS_SIGNING_SECRET);f.env._kv.set('revoked:'+p.jti,JSON.stringify({ts:new Date().toISOString()}));assert.equal((await req(student,'GET',undefined,f.studentToken)).status,401);const t=await verify(f.teacherToken,f.env.HPS_SIGNING_SECRET);f.env._kv.set('revoked:'+t.jti,JSON.stringify({ts:new Date().toISOString()}));assert.equal((await req(base)).status,401);});
 console.log(`${count} classroom API controls passed`);
}finally{f.close();}
