// Remote classroom operations R6 (#751) — Service layer of AT-31 with a sandbox adapter.
// No real provider, account or recipient exists in this test, and none is configured by the change.
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { localOps } from './harness/classroom-ops.mjs';
import { nextDeliveryState, maskAddress } from '../src/lib/classroom-delivery.ts';
import { CANDIDATE_CAPABILITY_V1 } from '../src/lib/measurement-core/index.ts';
const { registerDeliveryAdapter } = await import('../src/routes/classroom-delivery.ts');
let count = 0; async function check(name, fn) { await fn(); count++; console.log('PASS ' + name); }
const sha = (s) => createHash('sha256').update(s).digest('hex'); const meta = '{"s":1}', admin = { authorization: 'Basic ' + Buffer.from('x:pw').toString('base64') };
await check('controls: provider acceptance is not delivery, nothing means "opened", states only move forward', async () => {
  assert.equal(nextDeliveryState('sending', 'accepted'), 'provider_accepted'); assert.equal(nextDeliveryState('provider_accepted', 'delivered'), 'delivered'); assert.equal(nextDeliveryState('delivered', 'accepted'), null); assert.equal(nextDeliveryState('dry_run', 'delivered'), null); assert.equal(nextDeliveryState('failed', 'delivered'), null);
  assert.equal(nextDeliveryState('send_unknown', 'delivered'), 'delivered'); assert.equal(maskAddress('guardian@example.test'), 'g***@example.test');
});
const f = await localOps(); const seats = [{ seat_id: 'A1', student_id: 'student-a' }, { seat_id: 'A2', student_id: 'student-b' }, { seat_id: 'A3', student_id: 'student-c' }];
const sent = []; let mode = 'accept'; registerDeliveryAdapter({ id: 'sandbox', external: true, send: async (m) => { sent.push(m); if (mode === 'timeout') throw new Error('socket hang up'); return mode === 'reject' ? { status: 'rejected', reason: 'mailbox_unavailable' } : { status: 'accepted', provider_message_id: 'msg-' + sent.length.toString().padStart(4, '0') }; } });
try {
  await f.freeze(); assert.equal((await f.configure(seats, 0, { flags: { ops_observe: true, ops_commands: true, ops_collect: true, ops_reports: true, ops_delivery: true } })).status, 201);
  const conns = {}; for (const [i, s] of seats.slice(0, 2).entries()) { conns[s.student_id] = (await f.pair(s.seat_id, 1, i + 1)).conn.json; await f.request('/v1/classroom/ops/collect/consent', 'POST', { consent: true, purpose: 'class_report', notice_version: 'notice-v1' }, conns[s.student_id].credential); }
  const batch = (await f.request(f.base + '/report-batches', 'POST', { idempotency_key: crypto.randomUUID(), roster_revision: 1, purpose: 'class_report', notice_version: 'notice-v1', dry_run: false })).json.batch.id, B = f.base + '/report-batches/' + batch;
  for (const u of Object.keys(conns)) { const ev = `{"seq":1,"event_id":"e","type":"prompt","text":"${u} 가 기대 조건을 먼저 적음"}\n`; assert.equal((await f.uploadSnapshotAs(conns[u], batch, 1, ev)).status, 201); }
  await f.request(B + '/jobs', 'POST', {}); const runner = (await f.request(B + '/runner-grants', 'POST', {})).json.runner_credential; const keys = CANDIDATE_CAPABILITY_V1.capabilities.map((c) => c.key);
  for (let i = 0; i < 2; i++) { const j = (await f.request('/v1/classroom/ops/runner/claim', 'POST', {}, runner)).json.job; await f.request(`/v1/classroom/ops/runner/jobs/${j.id}/result`, 'POST', { lease_generation: j.lease_generation, draft: { format: 'hps-classroom-report-draft/1', versions: { capability_model: { id: CANDIDATE_CAPABILITY_V1.id, revision: CANDIDATE_CAPABILITY_V1.revision }, rubric: 'unknown', evaluator: 'none', renderer_revision: 'observation-report/1' }, findings: [{ capability: keys[0], status: 'observed', claim: '기대 조건을 먼저 정함', evidence: [{ event_id: 'e', quote: '기대 조건을 먼저 적음' }] }, ...keys.slice(1).map((capability) => ({ capability, status: 'unobserved', claim: '', evidence: [] }))], next_experiment: '다음에는 대안 2개를 먼저 적기' } }, runner); }
  const approveReport = async (student) => { const q = (await f.request(B + '/reports')).json.jobs.find((j) => j.student_id === student && j.draft_digest); const o = (await f.request(B + '/reports/' + q.id)).json; return f.request(B + `/reports/${q.id}/review`, 'PUT', { decision: 'approve', expected_revision: o.revision, draft_digest: o.draft_digest }); };
  assert.equal((await approveReport('student-a')).status, 200);
  await check('AT-31 recipients come only from the operator import: instructors cannot add one, a gallery-only person is refused, siblings are separate rows, addresses are masked', async () => {
    const body = { class_run_id: f.run, source_ref: 'customer-roster:2026-09', recipients: [{ student_id: 'student-a', recipient_ref: 'guardian-1', channel: 'email', address: 'guardian@example.test', viewer_check: { kind: 'phone_last4', value: '4821' } }, { student_id: 'student-b', recipient_ref: 'guardian-1', channel: 'email', address: 'guardian@example.test', viewer_check: { kind: 'phone_last4', value: '4821' } }] };
    assert.notEqual((await f.request('/admin/classroom/recipients', 'POST', body)).status, 201, 'an issuer Bearer is not the operator'); assert.equal((await f.request('/admin/classroom/recipients', 'POST', { ...body, recipients: [{ student_id: 'gallery-visitor', recipient_ref: 'x', channel: 'email', address: 'x@example.test' }] }, null, admin)).json.reason, 'recipient_invalid');
    assert.equal((await f.request('/admin/classroom/recipients', 'POST', { ...body, recipients: [{ ...body.recipients[0], address: 'not-an-address' }] }, null, admin)).status, 400); assert.equal((await f.request('/admin/classroom/recipients', 'POST', body, null, admin)).status, 201);
    const list = await f.request(B + '/recipients?template_revision=tmpl-1'); assert.equal(list.status, 200, list.raw); assert.ok(!list.raw.includes('guardian@example.test')); assert.deepEqual(list.json.will_send.map((r) => [r.student_id, r.address]), [['student-a', 'g***@example.test']]);
    assert.deepEqual(list.json.not_sending.map((r) => [r.student_id, r.reason]).sort(), [['student-b', 'no_approved_report'], ['student-c', 'no_approved_report']]); assert.equal(list.json.expected_messages, 1);
  });
  let approval;
  await check('AT-31 approval signs exactly what was shown; with no live account only a dry run can happen and it sends nothing', async () => {
    const shown = (await f.request(B + '/recipients?template_revision=tmpl-1')).json; assert.equal((await f.request(B + '/approve', 'POST', { template_revision: 'tmpl-1', channel: 'email', scope_hash: shown.scope_hash }, await f.teacher('sender', ['observe', 'deliver']))).status, 403);
    assert.equal((await f.request(B + '/approve', 'POST', { template_revision: 'tmpl-1', channel: 'email', scope_hash: 'f'.repeat(64) })).json.reason, 'scope_changed'); approval = (await f.request(B + '/approve', 'POST', { template_revision: 'tmpl-1', channel: 'email', scope_hash: shown.scope_hash })).json; assert.equal(approval.messages, 1);
    assert.equal((await f.request(B + '/deliver', 'POST', { approval_id: approval.approval_id, dry_run: false }, await f.teacher('reviewer', ['observe', 'review']))).status, 403);
    assert.equal((await f.request(B + '/deliver', 'POST', { approval_id: approval.approval_id, dry_run: false })).json.reason, 'delivery_provider_not_configured');
    const dry = await f.request(B + '/deliver', 'POST', { approval_id: approval.approval_id, dry_run: true }); assert.deepEqual([dry.status, dry.json.external_sends, dry.json.results[0].state], [202, 0, 'dry_run']); assert.equal(sent.length, 0);
  });
  await check('AT-31 a changed recipient or a newly approved report kills the approval before anything is sent', async () => {
    f.env.HPS_DELIVERY_PROVIDER = 'sandbox'; await f.request('/admin/classroom/recipients', 'POST', { class_run_id: f.run, source_ref: 'customer-roster:2026-09b', recipients: [{ student_id: 'student-a', recipient_ref: 'guardian-1', channel: 'email', address: 'new-guardian@example.test' }] }, null, admin);
    assert.equal((await f.request(B + '/deliver', 'POST', { approval_id: approval.approval_id, dry_run: false })).json.reason, 'approval_stale'); assert.equal(sent.length, 0);
    assert.equal((await approveReport('student-b')).status, 200); const shown = (await f.request(B + '/recipients?template_revision=tmpl-1')).json; assert.equal(shown.expected_messages, 2); approval = (await f.request(B + '/approve', 'POST', { template_revision: 'tmpl-1', channel: 'email', scope_hash: shown.scope_hash })).json;
  });
  await check('AT-31 send: ledger before adapter, accepted≠delivered, replay sends nothing, timeout is send_unknown and is not re-sent, duplicate webhooks are absorbed', async () => {
    mode = 'timeout'; const first = await f.request(B + '/deliver', 'POST', { approval_id: approval.approval_id, dry_run: false }); assert.deepEqual(first.json.results.map((r) => r.state), ['send_unknown', 'send_unknown']); assert.equal(sent.length, 2);
    mode = 'accept'; const again = await f.request(B + '/deliver', 'POST', { approval_id: approval.approval_id, dry_run: false }); assert.deepEqual(again.json.results.map((r) => [r.state, r.replay]), [['send_unknown', true], ['send_unknown', true]]); assert.equal(sent.length, 2, 'an unknown send is never repeated to find out');
    let d = (await f.request(B + '/deliveries')).json; assert.deepEqual([d.summary.by_state, d.summary.needs_operator], [{ dry_run: 1, send_unknown: 2 }, 2]);
    const [k1, k2] = d.deliveries.filter((x) => x.state === 'send_unknown').map((x) => x.delivery_key); assert.equal((await f.request(B + `/deliveries/${k1}/resolve`, 'POST', { outcome: 'provider_accepted', checked_ref: 'provider-console:lookup-1', provider_message_id: 'msg-lookup-1' })).status, 200); assert.equal((await f.request(B + `/deliveries/${k2}/resolve`, 'POST', { outcome: 'failed', checked_ref: 'provider-console:lookup-2' })).status, 200); assert.equal((await f.request(B + `/deliveries/${k1}/resolve`, 'POST', { outcome: 'failed', checked_ref: 'again' })).status, 409);
    const ev = (id, kind) => f.request('/admin/classroom/delivery-events', 'POST', { provider_event_id: id, provider_message_id: 'msg-lookup-1', kind }, null, admin); assert.equal((await ev('evt-0001', 'delivered')).json.state, 'delivered'); assert.equal((await ev('evt-0001', 'delivered')).json.duplicate, true); assert.equal((await ev('evt-0002', 'accepted')).json.applied, false, 'a late "accepted" does not roll delivered back');
    d = (await f.request(B + '/deliveries')).json; assert.deepEqual(d.summary.by_state, { dry_run: 1, delivered: 1, failed: 1 }); assert.ok(!JSON.stringify(d).match(/opened|read\b/));
    assert.ok(sent.every((m) => /^\/v1\/classroom\/report-links\/[A-Za-z0-9-]{40,80}$/.test(m.link) && !m.link.includes('student')), 'the message carries an opaque link, not the report or an id');
  });
  await check('AT-31 the link is opaque, expiring and revocable; it shows the approved report only and records each view', async () => {
    const link = sent[0].link, post = (path, check) => f.app.fetch(new Request('https://service.test' + path, { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: 'check=' + encodeURIComponent(check) }), f.env, { waitUntil() {} }).then(async (r) => ({ status: r.status, headers: r.headers, raw: await r.text() }));
    // Link viewer check (2026-09-20): having the link is not enough for a report that was sent to a real address.
    const ask = await f.request(link, 'GET', undefined, null); assert.equal(ask.status, 200); assert.ok(ask.raw.includes('보호자 휴대전화 번호 끝 4자리') && !ask.raw.includes('기대 조건을 먼저 적음'), 'GET asks; it shows nothing of the report');
    assert.equal((await f.request(link + '?format=json', 'GET', undefined, null)).json.reason, 'viewer_check_required'); const wrong = await post(link, '0000'); assert.equal(wrong.status, 403); assert.ok(wrong.raw.includes('남은 시도 4회') && !wrong.raw.includes('기대 조건을 먼저 적음'));
    const open = await f.request(link + '?format=json', 'POST', { check: '4821' }, null); assert.equal(open.status, 200, open.raw); assert.equal(open.headers.get('cache-control'), 'no-store'); assert.deepEqual(open.json.report.sections.map((s) => s.title).slice(0, 2), ['이번 수업에서 관찰된 행동', '판단이 바뀐 과정']); assert.ok(!open.raw.includes('example.test'));
    // What a person gets: a page, from the same composeReport() — no script, a closed CSP, provenance next to each quote, nothing numeric up front.
    const page = await post(link, ' 48-21 '); assert.equal(page.status, 200, 'separators typed on a phone are ignored'); assert.match(page.headers.get('content-type'), /^text\/html/); assert.match(page.headers.get('content-security-policy'), /default-src 'none'/);
    assert.ok(page.raw.includes('기대 조건을 먼저 적음') && page.raw.includes('학생이 직접 쓴 말') && page.raw.includes('아직 충분히 보지 못함')); assert.ok(!/<script|onerror=|javascript:/i.test(page.raw)); assert.ok(!/\d+\s*점|\d+\s*%|\d+\s*(위|등)\b|상위|하위|평균 대비/.test(page.raw.replace(/<style>[\s\S]*?<\/style>/, '')), 'no numeric score, rank, percentage or peer comparison on the page (saying it is NOT a score is fine)');
    assert.ok(!page.raw.includes('example.test') && !page.raw.includes(f.cohort), 'no address and no internal ids beyond the learner handle');
    assert.equal(f.db.prepare("SELECT count(*) n FROM ops_audit WHERE action='report_link_viewed'").get().n, 2, 'each open is recorded'); assert.equal(f.db.prepare("SELECT count(*) n FROM ops_audit WHERE action='report_link_check_failed'").get().n, 1);
    const dump = JSON.stringify([f.db.prepare('SELECT * FROM classroom_recipient_checks').all(), f.db.prepare('SELECT detail_json FROM ops_audit').all()]); assert.ok(!dump.includes('4821'), 'the check value is never stored or audited — only its salted HMAC'); assert.equal((await f.request('/v1/classroom/report-links/' + 'a'.repeat(64), 'GET', undefined, null)).status, 404);
    const key = f.db.prepare('SELECT d.delivery_key k FROM classroom_report_deliveries d JOIN classroom_report_links l ON l.id=d.link_id WHERE l.token_hash=?').get(sha(link.split('/').pop())).k; assert.equal((await f.request(B + `/deliveries/${key}/link`, 'DELETE')).status, 200); assert.equal((await f.request(link, 'GET', undefined, null)).status, 404);
    f.db.prepare('UPDATE classroom_report_links SET revoked_at=NULL,expires_at=1').run(); assert.equal((await f.request(link, 'GET', undefined, null)).status, 404); assert.ok(!f.db.prepare('SELECT group_concat(token_hash) h FROM classroom_report_links').get().h.includes(link.split('/').pop()));
  });
  await check('AT-31/32 delivery flag off → nothing reachable; rejected sends are failed, not unknown', async () => {
    mode = 'reject'; f.db.prepare("DELETE FROM classroom_report_deliveries WHERE state IN ('failed')").run(); const shown = (await f.request(B + '/recipients?template_revision=tmpl-2')).json; const ap = (await f.request(B + '/approve', 'POST', { template_revision: 'tmpl-2', channel: 'email', scope_hash: shown.scope_hash })).json; const r = await f.request(B + '/deliver', 'POST', { approval_id: ap.approval_id, dry_run: false }); assert.ok(r.json.results.every((x) => x.state === 'failed'));
    const rev = f.db.prepare('SELECT roster_revision r FROM class_run_ops').get().r; assert.equal((await f.configure(seats, rev, { flags: { ops_delivery: false }, lesson: undefined })).status, 200); assert.equal((await f.request(B + '/deliver', 'POST', { approval_id: ap.approval_id, dry_run: true })).json.reason, 'ops_delivery_disabled');
  });
  await check('viewer check: five wrong answers lock the link for good; a recipient without a check is never sent a real mail; changing the check kills the approval', async () => {
    { const rev = f.db.prepare('SELECT roster_revision r FROM class_run_ops').get().r; assert.equal((await f.configure(seats, rev, { flags: { ops_delivery: true }, lesson: undefined })).status, 200); mode = 'accept'; f.db.prepare('UPDATE classroom_report_links SET expires_at=?').run(Date.now() + 3600000); } // the previous control switched delivery off and expired every link
    // A recipient imported WITHOUT a check: visible to the approver, skipped by a live send, fine for a dry run.
    await f.request('/admin/classroom/recipients', 'POST', { class_run_id: f.run, source_ref: 'customer-roster:no-check', recipients: [{ student_id: 'student-a', recipient_ref: 'guardian-nocheck', channel: 'email', address: 'other@example.test' }] }, null, admin);
    const scope = (await f.request(B + '/recipients?template_revision=t9')).json, row = scope.will_send.find((x) => x.recipient_ref === 'guardian-nocheck'); assert.deepEqual([row.viewer_check, scope.live_send_blocked >= 1], ['missing', true]);
    const approval = (await f.request(B + '/approve', 'POST', { template_revision: 't9', channel: 'email', scope_hash: scope.scope_hash })).json.approval_id, before = sent.length;
    const live = await f.request(B + '/deliver', 'POST', { approval_id: approval, dry_run: false }); assert.equal(live.json.results.find((x) => x.recipient_ref === 'guardian-nocheck').state, 'not_sent_viewer_check_missing'); assert.ok(!sent.slice(before).some((m) => m.to === 'other@example.test'), 'no mail left for the recipient without a check');
    assert.equal(f.db.prepare("SELECT count(*) n FROM classroom_report_deliveries WHERE recipient_ref='guardian-nocheck' AND adapter='sandbox'").get().n, 0);
    const post = (path, check) => f.request(path + '?format=json', 'POST', { check }, null), link = sent.slice(before).find((m) => m.to === 'guardian@example.test').link; // a fresh, live link from the send above
    for (let i = 0; i < 4; i++) assert.equal((await post(link, '111' + i)).status, 403); assert.equal((await post(link, '1114')).status, 404, 'the fifth wrong answer closes the link');
    assert.equal((await post(link, '4821')).status, 404, 'even the right answer no longer opens a locked link: a new link is needed'); assert.equal(f.db.prepare("SELECT count(*) n FROM ops_audit WHERE action='report_link_locked'").get().n, 1);
    // The operator corrects the check after approval: what was approved is no longer what would be delivered.
    const s2 = (await f.request(B + '/recipients?template_revision=t10')).json, a2 = (await f.request(B + '/approve', 'POST', { template_revision: 't10', channel: 'email', scope_hash: s2.scope_hash })).json.approval_id;
    await f.request('/admin/classroom/recipients', 'POST', { class_run_id: f.run, source_ref: 'customer-roster:check-fixed', recipients: [{ student_id: 'student-a', recipient_ref: 'guardian-nocheck', channel: 'email', address: 'other@example.test', viewer_check: { kind: 'passphrase', value: '우리집 고양이 이름' } }] }, null, admin);
    assert.equal((await f.request(B + '/deliver', 'POST', { approval_id: a2, dry_run: false })).json.reason, 'approval_stale');
    for (const bad of [{ kind: 'phone_last4', value: '12' }, { kind: 'birth_mmdd', value: '1340' }, { kind: 'made_up', value: '1234' }, { kind: 'passphrase', value: 'abc' }]) assert.equal((await f.request('/admin/classroom/recipients', 'POST', { class_run_id: f.run, source_ref: 'customer-roster:bad', recipients: [{ student_id: 'student-a', recipient_ref: 'g-bad', channel: 'email', address: 'x@example.test', viewer_check: bad }] }, null, admin)).json.reason, 'viewer_check_invalid', JSON.stringify(bad));
  });
  console.log(`${count} remote classroom delivery controls passed`);
} finally { f.close(); }
