// Remote classroom operations R6 (#751) — Service layer of AT-31 with a sandbox adapter.
// No real provider, account or recipient exists in this test, and none is configured by the change.
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { localOps } from './harness/classroom-ops.mjs';
import { nextDeliveryState, maskAddress } from '../src/lib/classroom-delivery.ts';
import { CANDIDATE_CAPABILITY_V1 } from '../src/lib/measurement-core/index.ts';
const { registerDeliveryAdapter } = await import('../src/routes/classroom-delivery.ts');
let count = 0; async function check(name, fn) { await fn(); count++; console.log('PASS ' + name); }
const sha = (s) => createHash('sha256').update(s).digest('hex'); const meta = '{"s":1}', admin = { authorization: 'Basic ' + Buffer.from('x:pw').toString('base64') };
await check('controls: provider acceptance is not delivery, nothing means "opened", states only move forward', async () => {
  assert.equal(nextDeliveryState('sending', 'accepted'), 'provider_accepted'); assert.equal(nextDeliveryState('provider_accepted', 'delivered'), 'delivered'); assert.equal(nextDeliveryState('delivered', 'accepted'), null); assert.equal(nextDeliveryState('dry_run', 'delivered'), null); assert.equal(nextDeliveryState('failed', 'delivered'), null);
  assert.equal(nextDeliveryState('send_unknown', 'delivered'), 'delivered'); assert.equal(maskAddress('guardian@example.test'), 'g***@example.test');
});
const f = await localOps(); const seats = [{ seat_id: 'A1', student_id: 'student-a' }, { seat_id: 'A2', student_id: 'student-b' }, { seat_id: 'A3', student_id: 'student-c' }];
const sent = []; let mode = 'accept'; registerDeliveryAdapter({ id: 'sandbox', external: true, send: async (m) => { sent.push(m); if (mode === 'timeout') throw new Error('socket hang up'); return mode === 'reject' ? { status: 'rejected', reason: 'mailbox_unavailable' } : { status: 'accepted', provider_message_id: 'msg-' + sent.length.toString().padStart(4, '0') }; } });
try {
  await f.freeze(); assert.equal((await f.configure(seats, 0, { flags: { ops_observe: true, ops_commands: true, ops_collect: true, ops_reports: true, ops_delivery: true } })).status, 201);
  const conns = {}; for (const [i, s] of seats.slice(0, 2).entries()) { conns[s.student_id] = (await f.pair(s.seat_id, 1, i + 1)).conn.json; await f.request('/v1/classroom/ops/collect/consent', 'POST', { consent: true, purpose: 'class_report', notice_version: 'notice-v1' }, conns[s.student_id].credential); }
  const batch = (await f.request(f.base + '/report-batches', 'POST', { idempotency_key: crypto.randomUUID(), roster_revision: 1, purpose: 'class_report', notice_version: 'notice-v1', dry_run: false })).json.batch.id, B = f.base + '/report-batches/' + batch;
  for (const u of Object.keys(conns)) { const ev = `{"seq":1,"text":"${u} 가 기대 조건을 먼저 적음"}\n`; for (const [n, body] of [['session.meta.json', meta], ['events.jsonl', ev]]) await f.app.fetch(new Request(`https://service.test/v1/classroom/ops/collect/snapshots/${batch}/1/${n}`, { method: 'PUT', headers: { authorization: 'Bearer ' + conns[u].credential }, body }), f.env, { waitUntil() {} }); assert.equal((await f.request(`/v1/classroom/ops/collect/snapshots/${batch}/1/seal`, 'POST', { schema: 'hps-classroom-snapshot/1', files: [{ name: 'session.meta.json', bytes: Buffer.byteLength(meta), sha256: sha(meta) }, { name: 'events.jsonl', bytes: Buffer.byteLength(ev), sha256: sha(ev) }] }, conns[u].credential)).status, 201); }
  await f.request(B + '/jobs', 'POST', {}); const runner = (await f.request(B + '/runner-grants', 'POST', {})).json.runner_credential; const keys = CANDIDATE_CAPABILITY_V1.capabilities.map((c) => c.key);
  for (let i = 0; i < 2; i++) { const j = (await f.request('/v1/classroom/ops/runner/claim', 'POST', {}, runner)).json.job; await f.request(`/v1/classroom/ops/runner/jobs/${j.id}/result`, 'POST', { lease_generation: j.lease_generation, draft: { format: 'hps-classroom-report-draft/1', versions: { capability_model: { id: CANDIDATE_CAPABILITY_V1.id, revision: CANDIDATE_CAPABILITY_V1.revision }, rubric: 'unknown', evaluator: 'none', renderer_revision: 'observation-report/1' }, findings: [{ capability: keys[0], status: 'observed', claim: '기대 조건을 먼저 정함', evidence: [{ event_id: 'e', quote: '기대 조건을 먼저 적음' }] }, ...keys.slice(1).map((capability) => ({ capability, status: 'unobserved', claim: '', evidence: [] }))], next_experiment: '다음에는 대안 2개를 먼저 적기' } }, runner); }
  const approveReport = async (student) => { const q = (await f.request(B + '/reports')).json.jobs.find((j) => j.student_id === student && j.draft_digest); const o = (await f.request(B + '/reports/' + q.id)).json; return f.request(B + `/reports/${q.id}/review`, 'PUT', { decision: 'approve', expected_revision: o.revision, draft_digest: o.draft_digest }); };
  assert.equal((await approveReport('student-a')).status, 200);
  await check('AT-31 recipients come only from the operator import: instructors cannot add one, a gallery-only person is refused, siblings are separate rows, addresses are masked', async () => {
    const body = { class_run_id: f.run, source_ref: 'customer-roster:2026-09', recipients: [{ student_id: 'student-a', recipient_ref: 'guardian-1', channel: 'email', address: 'guardian@example.test' }, { student_id: 'student-b', recipient_ref: 'guardian-1', channel: 'email', address: 'guardian@example.test' }] };
    assert.notEqual((await f.request('/admin/classroom/recipients', 'POST', body)).status, 201, 'an issuer Bearer is not the operator'); assert.equal((await f.request('/admin/classroom/recipients', 'POST', { ...body, recipients: [{ student_id: 'gallery-visitor', recipient_ref: 'x', channel: 'email', address: 'x@example.test' }] }, null, admin)).json.reason, 'recipient_invalid');
    assert.equal((await f.request('/admin/classroom/recipients', 'POST', { ...body, recipients: [{ ...body.recipients[0], address: 'not-an-address' }] }, null, admin)).status, 400); assert.equal((await f.request('/admin/classroom/recipients', 'POST', body, null, admin)).status, 201);
    const list = await f.request(B + '/recipients?template_revision=tmpl-1'); assert.equal(list.status, 200, list.raw); assert.ok(!list.raw.includes('guardian@example.test')); assert.deepEqual(list.json.will_send.map((r) => [r.student_id, r.address]), [['student-a', 'g***@example.test']]);
    assert.deepEqual(list.json.not_sending.map((r) => [r.student_id, r.reason]).sort(), [['student-b', 'no_approved_report'], ['student-c', 'no_approved_report']]); assert.equal(list.json.expected_messages, 1);
  });
  let approval;
  await check('AT-31 approval signs exactly what was shown; with no live account only a dry run can happen and it sends nothing', async () => {
    const shown = (await f.request(B + '/recipients?template_revision=tmpl-1')).json; assert.equal((await f.request(B + '/approve', 'POST', { template_revision: 'tmpl-1', channel: 'email', scope_hash: shown.scope_hash }, await f.teacher('sender', ['observe', 'deliver']))).status, 403);
    assert.equal((await f.request(B + '/approve', 'POST', { template_revision: 'tmpl-1', channel: 'email', scope_hash: 'f'.repeat(64) })).json.reason, 'scope_changed'); approval = (await f.request(B + '/approve', 'POST', { template_revision: 'tmpl-1', channel: 'email', scope_hash: shown.scope_hash })).json; assert.equal(approval.messages, 1);
    assert.equal((await f.request(B + '/deliver', 'POST', { approval_id: approval.approval_id, dry_run: false }, await f.teacher('reviewer', ['observe', 'review']))).status, 403);
    assert.equal((await f.request(B + '/deliver', 'POST', { approval_id: approval.approval_id, dry_run: false })).json.reason, 'delivery_provider_not_configured');
    const dry = await f.request(B + '/deliver', 'POST', { approval_id: approval.approval_id, dry_run: true }); assert.deepEqual([dry.status, dry.json.external_sends, dry.json.results[0].state], [202, 0, 'dry_run']); assert.equal(sent.length, 0);
  });
  await check('AT-31 a changed recipient or a newly approved report kills the approval before anything is sent', async () => {
    f.env.HPS_DELIVERY_PROVIDER = 'sandbox'; await f.request('/admin/classroom/recipients', 'POST', { class_run_id: f.run, source_ref: 'customer-roster:2026-09b', recipients: [{ student_id: 'student-a', recipient_ref: 'guardian-1', channel: 'email', address: 'new-guardian@example.test' }] }, null, admin);
    assert.equal((await f.request(B + '/deliver', 'POST', { approval_id: approval.approval_id, dry_run: false })).json.reason, 'approval_stale'); assert.equal(sent.length, 0);
    assert.equal((await approveReport('student-b')).status, 200); const shown = (await f.request(B + '/recipients?template_revision=tmpl-1')).json; assert.equal(shown.expected_messages, 2); approval = (await f.request(B + '/approve', 'POST', { template_revision: 'tmpl-1', channel: 'email', scope_hash: shown.scope_hash })).json;
  });
  await check('AT-31 send: ledger before adapter, accepted≠delivered, replay sends nothing, timeout is send_unknown and is not re-sent, duplicate webhooks are absorbed', async () => {
    mode = 'timeout'; const first = await f.request(B + '/deliver', 'POST', { approval_id: approval.approval_id, dry_run: false }); assert.deepEqual(first.json.results.map((r) => r.state), ['send_unknown', 'send_unknown']); assert.equal(sent.length, 2);
    mode = 'accept'; const again = await f.request(B + '/deliver', 'POST', { approval_id: approval.approval_id, dry_run: false }); assert.deepEqual(again.json.results.map((r) => [r.state, r.replay]), [['send_unknown', true], ['send_unknown', true]]); assert.equal(sent.length, 2, 'an unknown send is never repeated to find out');
    let d = (await f.request(B + '/deliveries')).json; assert.deepEqual([d.summary.by_state, d.summary.needs_operator], [{ dry_run: 1, send_unknown: 2 }, 2]);
    const [k1, k2] = d.deliveries.filter((x) => x.state === 'send_unknown').map((x) => x.delivery_key); assert.equal((await f.request(B + `/deliveries/${k1}/resolve`, 'POST', { outcome: 'provider_accepted', checked_ref: 'provider-console:lookup-1', provider_message_id: 'msg-lookup-1' })).status, 200); assert.equal((await f.request(B + `/deliveries/${k2}/resolve`, 'POST', { outcome: 'failed', checked_ref: 'provider-console:lookup-2' })).status, 200); assert.equal((await f.request(B + `/deliveries/${k1}/resolve`, 'POST', { outcome: 'failed', checked_ref: 'again' })).status, 409);
    const ev = (id, kind) => f.request('/admin/classroom/delivery-events', 'POST', { provider_event_id: id, provider_message_id: 'msg-lookup-1', kind }, null, admin); assert.equal((await ev('evt-0001', 'delivered')).json.state, 'delivered'); assert.equal((await ev('evt-0001', 'delivered')).json.duplicate, true); assert.equal((await ev('evt-0002', 'accepted')).json.applied, false, 'a late "accepted" does not roll delivered back');
    d = (await f.request(B + '/deliveries')).json; assert.deepEqual(d.summary.by_state, { dry_run: 1, delivered: 1, failed: 1 }); assert.ok(!JSON.stringify(d).match(/opened|read\b/));
    assert.ok(sent.every((m) => /^\/v1\/classroom\/report-links\/[A-Za-z0-9-]{40,80}$/.test(m.link) && !m.link.includes('student')), 'the message carries an opaque link, not the report or an id');
  });
  await check('AT-31 the link is opaque, expiring and revocable; it shows the approved report only and records each view', async () => {
    const link = sent[0].link, open = await f.request(link, 'GET', undefined, null); assert.equal(open.status, 200, open.raw); assert.equal(open.headers.get('cache-control'), 'no-store'); assert.deepEqual(open.json.report.sections.map((s) => s.title).slice(0, 2), ['이번 수업에서 관찰된 행동', '판단이 바뀐 과정']); assert.ok(!open.raw.includes('example.test'));
    assert.equal(f.db.prepare("SELECT count(*) n FROM ops_audit WHERE action='report_link_viewed'").get().n, 1); assert.equal((await f.request('/v1/classroom/report-links/' + 'a'.repeat(64), 'GET', undefined, null)).status, 404);
    const key = f.db.prepare('SELECT d.delivery_key k FROM classroom_report_deliveries d JOIN classroom_report_links l ON l.id=d.link_id WHERE l.token_hash=?').get(sha(link.split('/').pop())).k; assert.equal((await f.request(B + `/deliveries/${key}/link`, 'DELETE')).status, 200); assert.equal((await f.request(link, 'GET', undefined, null)).status, 404);
    f.db.prepare('UPDATE classroom_report_links SET revoked_at=NULL,expires_at=1').run(); assert.equal((await f.request(link, 'GET', undefined, null)).status, 404); assert.ok(!f.db.prepare('SELECT group_concat(token_hash) h FROM classroom_report_links').get().h.includes(link.split('/').pop()));
  });
  await check('AT-31/32 delivery flag off → nothing reachable; rejected sends are failed, not unknown', async () => {
    mode = 'reject'; f.db.prepare("DELETE FROM classroom_report_deliveries WHERE state IN ('failed')").run(); const shown = (await f.request(B + '/recipients?template_revision=tmpl-2')).json; const ap = (await f.request(B + '/approve', 'POST', { template_revision: 'tmpl-2', channel: 'email', scope_hash: shown.scope_hash })).json; const r = await f.request(B + '/deliver', 'POST', { approval_id: ap.approval_id, dry_run: false }); assert.ok(r.json.results.every((x) => x.state === 'failed'));
    const rev = f.db.prepare('SELECT roster_revision r FROM class_run_ops').get().r; assert.equal((await f.configure(seats, rev, { flags: { ops_delivery: false }, lesson: undefined })).status, 200); assert.equal((await f.request(B + '/deliver', 'POST', { approval_id: ap.approval_id, dry_run: true })).json.reason, 'ops_delivery_disabled');
  });
  console.log(`${count} remote classroom delivery controls passed`);
} finally { f.close(); }
