import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm, symlink } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { LocalReviewService } from '../src/localReviewService.ts';
import { recentLocalSessions } from '../src/localSessionDiscovery.ts';
import { parseLocalTranscript, parseLocalTranscriptFile } from '../src/localTranscript.ts';
const root = await mkdtemp(join(tmpdir(), 'hps-session-observation-'));
const at = '2026-09-14T12:00:00Z';
const message = (text, role='user') => ({timestamp:at,type:'response_item',payload:{type:'message',role,content:[{type:'input_text',text}]}});
const rows = [{type:'session_meta',payload:{id:'session-one',cwd:'/project'}},{type:'turn_context',timestamp:at,payload:{model:'model-one',effort:'high'}},message('Compare the actual evidence.'),message('I claim the checks passed.','assistant')];
const serialize = r => r.map(x=>JSON.stringify(x)).join('\n');
try {
 const dir=join(root,'.codex/sessions/2026/09/14'); await mkdir(dir,{recursive:true});
 await writeFile(join(dir,'one.jsonl'),serialize(rows));
 await writeFile(join(dir,'foreign.jsonl'),serialize([{type:'session_meta',payload:{id:'foreign',cwd:'/unrelated'}},message('Not in scope')]));
 await symlink(join(dir,'one.jsonl'),join(dir,'linked.jsonl'));
 const claudeDir=join(root,'.claude/projects/-project');await mkdir(claudeDir,{recursive:true});
 await writeFile(join(claudeDir,'claude.jsonl'),serialize([{timestamp:at,type:'user',sessionId:'claude-one',cwd:'/project',message:{role:'user',content:'Check the evidence'}}]));
 const sessions=await recentLocalSessions(root,'/project',Date.parse(at));assert.equal(sessions.length,2);assert.deepEqual(new Set(sessions.map(s=>s.host)),new Set(['codex','claude-code']));assert.ok(!JSON.stringify(sessions).includes('Compare the actual'));
 const streamed=await parseLocalTranscriptFile(join(dir,'one.jsonl'),'codex');assert.deepEqual(streamed,parseLocalTranscript(serialize(rows),'codex'));
 const recovery = new LocalReviewService(join(root,'recovery'));
 const originalWrite = recovery.store.write.bind(recovery.store); let failOnce = true;
 recovery.store.write = async (key,value,options) => { if (key.startsWith('imports/') && failOnce) {failOnce=false;throw Error('simulated_disk_failure');} return originalWrite(key,value,options); };
 await assert.rejects(recovery.import(serialize(rows),'codex','/project'), /simulated_disk_failure/);
 const recovered = await new LocalReviewService(join(root,'recovery')).import(serialize(rows),'codex','/project');
 assert.equal(recovered.observations.length,2);assert.equal((await recovery.record.records()).tasks.length,1);
 const service=new LocalReviewService(join(root,'storage'));const first=await service.import(serialize(rows),'codex','/project');
 assert.deepEqual(first.interpretation.versions.work_ai_models,['model-one']);
 await service.review(first.task.id,'FRAMING','correct','Asked for comparison',[first.observations[0].key]);
 await assert.rejects(service.review(first.task.id,'FRAMING','correct','bad',['observations/foreign']),/invalid_evidence/);
 const pending=await service.preview(first.task.id,false);
 const nextRows=[...rows,{type:'turn_context',timestamp:at,payload:{model:'model-two',effort:'medium'}},message('Keep the uncertainty visible.')];
 const next=await service.import(serialize(nextRows)+'\n{"partial":','codex','/project');
 assert.equal(next.task.id,first.task.id);assert.equal(next.observations.length,3);assert.equal(next.reviews.length,1);assert.equal(next.interpretation.revision,2);assert.equal(next.source.snapshots.length,2);
 assert.match(next.reviews[0].note,/Evidence: observations/);assert.deepEqual(next.interpretation.versions.work_ai_models,['model-one','model-two']);
 await assert.rejects(service.submit(first.task.id,pending.digest),/preview_required/);
 assert.equal((await service.record.records()).tasks.length,1);
 const secondPreview=await service.preview(first.task.id,true);await service.submit(first.task.id,secondPreview.digest);
 const reopened=await new LocalReviewService(join(root,'storage')).card(first.task.id);assert.equal(reopened.receipts.length,1);assert.equal(reopened.interpretation.revision,2);
 await service.improvement(first.task.id,'Write success criteria before delegating');
 const otherRows=[{type:'session_meta',payload:{id:'session-two',cwd:'/project'}},message('Try the selected action')];
 const other=await service.import(serialize(otherRows),'codex','/project');
 await service.followUp(other.task.id,'next-'+first.task.id,'tried','');
 let improvement=(await service.record.records()).improvements[0];assert.equal(improvement.follow_ups[0].result,'unconfirmed');
 await service.followUp(other.task.id,improvement.id,'tried','I recorded criteria before delegating.');
 improvement=(await service.record.records()).improvements[0];assert.equal(improvement.follow_ups[1].result,'observed');
 await assert.rejects(service.followUp(first.task.id,improvement.id,'tried','same task'),/same_task/);
 await service.delete(first.task.id);
 await assert.rejects(service.import(serialize([...nextRows,message('later')]),'codex','/project'),/task_deleted/);
 const many=[rows[0],...Array.from({length:502},(_,i)=>message('Message '+i))];
 const window=parseLocalTranscript(serialize(many),'codex');assert.equal(window.batch.events.length,500);assert.equal(window.batch.events[0].seq,3);assert.ok(window.exclusions.some(x=>x.includes('500')));
 assert.throws(()=>parseLocalTranscript(serialize([rows[0], ...Array.from({length:10002},(_,i)=>message('Message '+i))]),'codex'), /session_message_limit_exceeded/);
 assert.throws(()=>parseLocalTranscript(serialize(rows)+'\n{bad\n'+JSON.stringify(message('later')),'codex'),/invalid_transcript_json/);
 console.log('PASS discovery, model changes, partial-tail/window limits, same-task refresh, evidence binding, preview invalidation, restart, improvement/follow-up, deletion');
} finally {await rm(root,{recursive:true,force:true});}
