import assert from 'node:assert/strict';
import {NativeObservationRecorder} from '../src/nativeObservationRecorder.ts';
const context={format:'hps-observation/1',scope:'synthetic-a',session:'session-a',program:'m2026.09.08-1'};
const a=new NativeObservationRecorder(context);
a.record('task1','user','새 직원 안내문');a.toolRequest('task1','t1','Write(draft.md)');a.toolRequest('task1','t1','Write(draft.md)');
a.record('task1','approval','정책 허용',{tool_id:'t1',actor:'policy',outcome:'allowed'});
a.record('task1','tool_result','Write(draft.md)',{tool_id:'t1',outcome:'success'});
assert.equal(a.batch.events.length,4);assert.equal(a.batch.events[2].actor,'policy');
const saved=a.snapshot(), resumed=new NativeObservationRecorder(context,saved);
resumed.record('task2','user','새 과제');assert.equal(resumed.batch.events[4].seq,5);assert.equal(saved.events.length,4);
assert.throws(()=>new NativeObservationRecorder({...context,scope:'synthetic-b'},saved));
assert.throws(()=>new NativeObservationRecorder({...context,session:'session-b'},saved));
assert.throws(()=>new NativeObservationRecorder({...context,program:'m2026.09.08-2'},saved));
assert.equal(new NativeObservationRecorder(context).batch.events.length,0);
console.log('PASS host recorder: role separation, policy approval, dedupe, restart and identity/program isolation');
const oversized=new NativeObservationRecorder(context);
oversized.record('t','user','x'.repeat(20001));
assert.equal(new NativeObservationRecorder(context,oversized.snapshot()).batch.incomplete,true);
console.log('PASS truncated records remain explicitly incomplete after reload');
const privateInput=new NativeObservationRecorder(context),sentinel='sk-ant-'+'Z'.repeat(28);
privateInput.record('t','user','가상 비밀 '+sentinel);
assert.ok(!JSON.stringify(privateInput.snapshot()).includes(sentinel));
console.log('PASS credentials removed before local observation persistence');
