// SDK tool-drift guard (#375). Studio's tool surface is a hand-maintained
// allowlist (SDK_READ/WRITE/AGENT_TOOL_NAMES, SEARCH_TOOLS, Bash, MCP browser
// tools). Deny-by-default is the right design, but it only stays current if
// someone notices when the Agent SDK moves: bump @anthropic-ai/claude-agent-sdk,
// a new tool ships, and the model quietly can't use it — denied exactly like a
// routine policy denial, in a console nobody reads.
//
// This test turns that silent drift into a green/red signal at PR time. It
// enumerates the INSTALLED SDK's actual tool surface (the ToolInputSchemas
// union in sdk-tools.d.ts — generated by json-schema-to-typescript, so it is
// canonical and enumerable at test time) and asserts every tool is either
// CLASSIFIED by the policy matrix (isClassifiedSdkToolName) or explicitly
// listed in ACKNOWLEDGED_UNSUPPORTED below — the record of tools we have looked
// at and consciously chosen not to wire. A genuinely NEW SDK tool is neither,
// so it fails here and forces a look instead of shipping as silence.
//
// Run: node --experimental-strip-types test/sdk-tool-drift.smoke.mjs

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

const { isClassifiedSdkToolName, evaluateSdkToolUse } = await import("../src/sdkCoachHelpers.ts");

// ─── the drift flag on evaluateSdkToolUse denials (#375, unit) ───────────────
// The mechanical half of the fix: the not-granted gate flags a name the matrix
// has never classified as `drift`, distinct from a routine profile denial.
{
  const adultRW = ["Read", "Grep", "Glob", "Write", "Edit"];

  // Classified names denied by policy are NOT drift (expected, high-volume).
  for (const name of ["Bash", "WebFetch", "Read", "Write", "Edit", "Agent"]) {
    assert.ok(isClassifiedSdkToolName(name), `${name} must be a classified tool name`);
  }
  const bash = evaluateSdkToolUse({ toolName: "Bash", input: { command: "ls" }, permittedTools: adultRW });
  assert.ok(bash.decision === "deny" && !bash.drift, "Bash denial is routine policy, not drift");

  // A name the matrix has never heard of IS drift, and stays a fail-closed deny.
  for (const unknown of ["MysteryTool", "mcp__github__create_pr", "ComputerUse", "Websearch2"]) {
    assert.ok(!isClassifiedSdkToolName(unknown), `${unknown} must be unclassified`);
    const v = evaluateSdkToolUse({ toolName: unknown, input: {}, permittedTools: adultRW });
    assert.equal(v.decision, "deny", `${unknown} still fails closed`);
    assert.equal(v.drift, true, `${unknown} is flagged as SDK tool drift`);
  }
}

// ─── the installed SDK's tool surface is fully accounted for (#375, CI) ──────
{
  // Locate the installed SDK type definitions. The extension keeps the SDK as a
  // devDependency (never prod — see sdk-gateway.smoke.mjs); `npm test` installs
  // it, so this file is present when the suite runs.
  const dtsPath = join(here, "..", "node_modules", "@anthropic-ai", "claude-agent-sdk", "sdk-tools.d.ts");
  let dts;
  try {
    dts = readFileSync(dtsPath, "utf8");
  } catch {
    assert.fail(
      `Cannot read the installed Agent SDK tool schema at ${dtsPath}. ` +
        `Run \`npm install\` in extensions/hypeproof-chat before the smoke suite so drift can be checked against the real SDK.`,
    );
  }

  // The canonical tool surface: the `export type ToolInputSchemas = A | B | …;`
  // union. Each member is a `<TypeName>Input` interface; the runtime tool name
  // is the type name minus the "Input" suffix, with the handful of File* names
  // aliased to the built-in tool names the SDK actually emits at runtime.
  const unionMatch = dts.match(/export type ToolInputSchemas\s*=([\s\S]*?);/);
  assert.ok(unionMatch, "sdk-tools.d.ts must declare the ToolInputSchemas union");
  const inputTypeNames = [...unionMatch[1].matchAll(/([A-Za-z0-9_]+)Input\b/g)].map((m) => m[1]);
  // ToolOutputSchemas is referenced from the union tail but is not a tool input.
  const toolTypeNames = [...new Set(inputTypeNames)].filter((n) => n !== "ToolOutputSchemas");
  assert.ok(toolTypeNames.length >= 30, `expected a substantial SDK tool surface, got ${toolTypeNames.length}`);

  // json-schema-to-typescript names the file tools FileRead/FileWrite/FileEdit;
  // the SDK emits them at runtime as Read/Write/Edit (verified against sdk.mjs).
  const TYPE_TO_TOOL_NAME = { FileRead: "Read", FileWrite: "Write", FileEdit: "Edit" };
  const toolName = (typeName) => TYPE_TO_TOOL_NAME[typeName] ?? typeName;

  // Tools that exist in the SDK but Studio's chat-first coach deliberately does
  // NOT classify/grant (#282 Phase 2 is read/write/search/subagent/browser
  // only). This list is the "we looked and chose not to wire it" record: adding
  // a name here is a conscious decision, and a NEW SDK tool that is neither
  // classified nor listed here fails the assertion below — which is the point.
  const ACKNOWLEDGED_UNSUPPORTED = new Set([
    "Artifact",
    "AskUserQuestion",
    "ClaudeDesign",
    "CronCreate",
    "CronDelete",
    "CronList",
    "EnterPlanMode",
    "EnterWorktree",
    "ExitPlanMode",
    "ExitWorktree",
    "ListMcpResources",
    "Mcp",
    "Monitor",
    "Projects",
    "PushNotification",
    "ReadMcpResource",
    "ReadMcpResourceDir",
    "RemoteTrigger",
    "REPL",
    "ReportFindings",
    "ScheduleWakeup",
    "ShowOnboardingRolePicker",
    "TaskCreate",
    "TaskGet",
    "TaskList",
    "TaskOutput",
    "TaskStop",
    "TaskUpdate",
    "TodoWrite",
    "Workflow",
  ]);

  const unaccounted = [];
  let classifiedCount = 0;
  for (const typeName of toolTypeNames) {
    const name = toolName(typeName);
    if (isClassifiedSdkToolName(name)) {
      classifiedCount += 1;
      continue;
    }
    if (ACKNOWLEDGED_UNSUPPORTED.has(name)) continue;
    unaccounted.push(name);
  }

  assert.deepEqual(
    unaccounted,
    [],
    `\nSDK TOOL DRIFT: the installed @anthropic-ai/claude-agent-sdk exposes tool(s) the policy matrix neither ` +
      `classifies nor deliberately excludes:\n  ${unaccounted.join(", ")}\n` +
      `If Studio should handle a tool, wire it into SDK_*_TOOL_NAMES / the *_TOOLS sets in sdkCoachHelpers.ts. ` +
      `If it should stay denied, add it to ACKNOWLEDGED_UNSUPPORTED in this test. Either way, make the choice on purpose.`,
  );

  // Sanity: the classified count matches the built-in surface we grant today
  // (Read, Write, Edit, Grep, Glob, NotebookEdit, WebFetch, WebSearch, Agent).
  // If this drops, a tool we DO classify vanished from the SDK — also worth a look.
  assert.ok(
    classifiedCount >= 8,
    `expected the SDK to still expose the built-in tools Studio classifies; only ${classifiedCount} matched`,
  );
}

console.log("✓ #375: SDK tool drift — denials flagged apart + installed SDK surface fully accounted for");
